// src/enums/error-code.enum.ts

export enum ERROR_CODE_ENUM {
  // Auth related
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN',
  AUTH_REFRESH_TOKEN_NOT_FOUND = 'AUTH_REFRESH_TOKEN_NOT_FOUND',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',

  // Validation and resource related
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',

  // Database related
  DB_DUPLICATE_KEY = 'DB_DUPLICATE_KEY',
  DB_CONNECTION_FAILED = 'DB_CONNECTION_FAILED',
  DB_NOT_FOUND = 'DB_NOT_FOUND',

  // Request/Response related
  BAD_REQUEST = 'BAD_REQUEST',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  // Server/Unknown
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  JSON_PARSE_ERROR = 'JSON_PARSE_ERROR',
}

export type ERROR_CODE_ENUM_TYPE = (typeof ERROR_CODE_ENUM)[keyof typeof ERROR_CODE_ENUM];
